name: Publish Specs

on:
  push:
    branches: [ master ]

env:
  SUBSCRIPTION: e2d5340c-6f88-4bc6-8c1e-c5792ec4262b
  
jobs:

  generate_matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Matrix
        id: generate_matrix
        run: echo "::set-output name=templates::$(find . -name 'componentdeploy.json' | jq -R -s -c 'split("\n")[:-1]')"

    outputs:
      templates: ${{ steps.generate_matrix.outputs.templates }}

  publish_spec:
    name: Publish Spec
    needs: generate_matrix
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5
      matrix:
        template: ${{ fromJson(needs.generate_matrix.outputs.templates) }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Publish Spec
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            TEMPLATE="${{ matrix.template }}"
            az ts create --subscription $SUBSCRIPTION --resource-group ComponentSpecs --location "eastus" --name "$(basename $(dirname $TEMPLATE))" --version "$(cat $TEMPLATE | jq --raw-output '.contentVersion')" --template-file "$TEMPLATE" --yes
