name: Publish Specs

on:
  push:
    branches: [ master ]

env:
  SUBSCRIPTION: " "
  RESOURCEGROUP: "ComponentSpecs"

jobs:

  generate_matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Matrix
        id: generate_matrix
        run: echo "::set-output name=templates::$(find . -name 'componentdeploy.json' | jq -R -s -c 'split("\n")[:-1]')"

    outputs:
      templates: ${{ steps.generate_matrix.outputs.templates }}

  publish_catalog:
    name: Publish Catalog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hugo Install
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Catalog Storage
        id: storage_deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION }}
          resourceGroupName: ${{ env.RESOURCEGROUP }}
          template: ./_catalog/azuredeploy.json
      - name: Create Catalog WebSite
        run: az storage blob service-properties update --account-name ${{ steps.storage_deploy.outputs.accountName }} --static-website --index-document index.html 
      - name: Prepare Catalog
        run: |
          find ./_catalog/site/content/* -type d -delete
          for f in $(find . -type f -name 'componentdeploy.json'); do
            cp -r $(dirname $f) ./_catalog/site/content
          done
          find ./_catalog/site/content/ -type f -name 'componentdeploy.json' -delete
          for f in $(find ./_catalog/site/content/ -type f -name 'readme.md'); do
            mv $f $(dirname $f)/_index.md
          done
          sed -i "s/baseUrl = .*/baseUrl = \"$( az storage account show --subscription ${{ env.SUBSCRIPTION }} --resource-group ${{ env.RESOURCEGROUP }} --name ${{ steps.storage_deploy.outputs.accountName }} --query "primaryEndpoints.web" -o tsv )\"/g ./_catalog/site/config.toml
      - name: Build Catalog
        working-directory: ./_catalog/site
        run: hugo
      - name: Upload Catalog
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          connection_string: ${{ steps.storage_deploy.outputs.connectionString }}
          source_dir: ./_catalog/site/public
          container_name: $web
          sync: true

  publish_spec:
    name: Publish Spec
    needs: generate_matrix
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5
      matrix:
        template: ${{ fromJson(needs.generate_matrix.outputs.templates) }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Publish Spec
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            TEMPLATE="${{ matrix.template }}"
            az ts create --subscription "$SUBSCRIPTION" --resource-group "$RESOURCEGROUP" --location "eastus" --name "$(basename $(dirname $TEMPLATE))" --version "$(cat $TEMPLATE | jq --raw-output '.contentVersion')" --template-file "$TEMPLATE" --yes
